name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Debug environment variables
        run: |
          echo "Checking if secrets are set..."
          if [ -n "${{ secrets.CONTENTFUL_SPACE_ID }}" ]; then
            echo "CONTENTFUL_SPACE_ID is set"
            echo "Length of SPACE_ID: ${#CONTENTFUL_SPACE_ID}"
          else
            echo "CONTENTFUL_SPACE_ID is not set"
          fi
          if [ -n "${{ secrets.CONTENTFUL_DELIVERY_TOKEN }}" ]; then
            echo "CONTENTFUL_DELIVERY_TOKEN is set"
            echo "Length of DELIVERY_TOKEN: ${#CONTENTFUL_DELIVERY_TOKEN}"
          else
            echo "CONTENTFUL_DELIVERY_TOKEN is not set"
          fi
          if [ -n "${{ secrets.CONTENTFUL_PREVIEW_TOKEN }}" ]; then
            echo "CONTENTFUL_PREVIEW_TOKEN is set"
            echo "Length of PREVIEW_TOKEN: ${#CONTENTFUL_PREVIEW_TOKEN}"
          else
            echo "CONTENTFUL_PREVIEW_TOKEN is not set"
          fi
          
      - name: Replace environment variables
        run: |
          echo "Starting environment variable replacement..."
          
          # Create a backup of the original file
          cp contentful-config.js contentful-config.js.bak
          
          # Show the original file content
          echo "Original file content:"
          head -n 5 contentful-config.js
          
          # Replace the placeholders using sed
          sed -i "s/space: 'CONTENTFUL_SPACE_ID'/space: '${{ secrets.CONTENTFUL_SPACE_ID }}'/" contentful-config.js
          sed -i "s/deliveryToken: 'CONTENTFUL_DELIVERY_TOKEN'/deliveryToken: '${{ secrets.CONTENTFUL_DELIVERY_TOKEN }}'/" contentful-config.js
          sed -i "s/previewToken: 'CONTENTFUL_PREVIEW_TOKEN'/previewToken: '${{ secrets.CONTENTFUL_PREVIEW_TOKEN }}'/" contentful-config.js
          
          # Show the modified file content
          echo "Modified file content:"
          head -n 5 contentful-config.js
          
          # Verify the replacements
          echo "Verifying replacements..."
          if grep -q "CONTENTFUL_SPACE_ID" contentful-config.js; then
            echo "WARNING: SPACE_ID placeholder still present"
          else
            echo "SPACE_ID replaced successfully"
          fi
          
          if grep -q "CONTENTFUL_DELIVERY_TOKEN" contentful-config.js; then
            echo "WARNING: DELIVERY_TOKEN placeholder still present"
          else
            echo "DELIVERY_TOKEN replaced successfully"
          fi
          
          if grep -q "CONTENTFUL_PREVIEW_TOKEN" contentful-config.js; then
            echo "WARNING: PREVIEW_TOKEN placeholder still present"
          else
            echo "PREVIEW_TOKEN replaced successfully"
          fi
          
          # Add a timestamp to prevent caching
          echo "// Last updated: $(date)" >> contentful-config.js
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 