name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Debug environment variables
        run: |
          echo "Checking if secrets are set..."
          if [ -n "${{ secrets.CONTENTFUL_SPACE_ID }}" ]; then
            echo "CONTENTFUL_SPACE_ID is set"
            echo "Length of SPACE_ID: ${#CONTENTFUL_SPACE_ID}"
          else
            echo "CONTENTFUL_SPACE_ID is not set"
          fi
          if [ -n "${{ secrets.CONTENTFUL_DELIVERY_TOKEN }}" ]; then
            echo "CONTENTFUL_DELIVERY_TOKEN is set"
            echo "Length of DELIVERY_TOKEN: ${#CONTENTFUL_DELIVERY_TOKEN}"
          else
            echo "CONTENTFUL_DELIVERY_TOKEN is not set"
          fi
          if [ -n "${{ secrets.CONTENTFUL_PREVIEW_TOKEN }}" ]; then
            echo "CONTENTFUL_PREVIEW_TOKEN is set"
            echo "Length of PREVIEW_TOKEN: ${#CONTENTFUL_PREVIEW_TOKEN}"
          else
            echo "CONTENTFUL_PREVIEW_TOKEN is not set"
          fi
          
      - name: Replace environment variables
        env:
          SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          DELIVERY_TOKEN: ${{ secrets.CONTENTFUL_DELIVERY_TOKEN }}
          PREVIEW_TOKEN: ${{ secrets.CONTENTFUL_PREVIEW_TOKEN }}
        run: |
          echo "Starting environment variable replacement..."
          
          # Create a Node.js script to handle the replacement
          cat > replace.js << 'EOF'
          const fs = require('fs');
          
          // Read the original file
          const content = fs.readFileSync('contentful-config.js', 'utf8');
          
          // Get environment variables
          const spaceId = process.env.SPACE_ID;
          const deliveryToken = process.env.DELIVERY_TOKEN;
          const previewToken = process.env.PREVIEW_TOKEN;
          
          // Log the lengths of the values (not the actual values)
          console.log('Space ID length:', spaceId ? spaceId.length : 0);
          console.log('Delivery Token length:', deliveryToken ? deliveryToken.length : 0);
          console.log('Preview Token length:', previewToken ? previewToken.length : 0);
          
          if (!spaceId || !deliveryToken || !previewToken) {
            console.error('Missing environment variables');
            process.exit(1);
          }
          
          // Create the new configuration object
          const configContent = `// Contentful API Configuration
const contentfulConfig = {
    space: '${spaceId}',
    deliveryToken: '${deliveryToken}',
    previewToken: '${previewToken}',
    environment: 'master',
    postsPerPage: 3
};`;
          
          // Get the rest of the file content
          const restOfFile = content.split('\n').slice(7).join('\n');
          
          // Combine the new config with the rest of the file
          const newContent = configContent + '\n' + restOfFile;
          
          // Write the modified content back
          fs.writeFileSync('contentful-config.js', newContent);
          
          // Verify the replacements
          const finalContent = fs.readFileSync('contentful-config.js', 'utf8');
          const hasPlaceholders = 
            finalContent.includes('CONTENTFUL_SPACE_ID') ||
            finalContent.includes('CONTENTFUL_DELIVERY_TOKEN') ||
            finalContent.includes('CONTENTFUL_PREVIEW_TOKEN');
          
          if (hasPlaceholders) {
            console.error('WARNING: Some placeholders were not replaced');
            console.error('First few lines of the file:');
            console.error(finalContent.split('\n').slice(0, 5).join('\n'));
            process.exit(1);
          }
          
          console.log('Successfully replaced all placeholders');
          EOF
          
          # Run the Node.js script
          node replace.js
          
          # Verify the replacements
          echo "Verifying replacements..."
          if grep -q "CONTENTFUL_SPACE_ID" contentful-config.js; then
            echo "WARNING: SPACE_ID placeholder still present"
            cat contentful-config.js | head -n 5
            exit 1
          else
            echo "SPACE_ID replaced successfully"
          fi
          
          if grep -q "CONTENTFUL_DELIVERY_TOKEN" contentful-config.js; then
            echo "WARNING: DELIVERY_TOKEN placeholder still present"
            cat contentful-config.js | head -n 5
            exit 1
          else
            echo "DELIVERY_TOKEN replaced successfully"
          fi
          
          if grep -q "CONTENTFUL_PREVIEW_TOKEN" contentful-config.js; then
            echo "WARNING: PREVIEW_TOKEN placeholder still present"
            cat contentful-config.js | head -n 5
            exit 1
          else
            echo "PREVIEW_TOKEN replaced successfully"
          fi
          
          # Add a timestamp to prevent caching
          echo "// Last updated: $(date)" >> contentful-config.js
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 