name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Debug environment variables
        run: |
          echo "Checking if secrets are set..."
          if [ -n "${{ secrets.CONTENTFUL_SPACE_ID }}" ]; then
            echo "CONTENTFUL_SPACE_ID is set"
          else
            echo "CONTENTFUL_SPACE_ID is not set"
          fi
          if [ -n "${{ secrets.CONTENTFUL_DELIVERY_TOKEN }}" ]; then
            echo "CONTENTFUL_DELIVERY_TOKEN is set"
          else
            echo "CONTENTFUL_DELIVERY_TOKEN is not set"
          fi
          if [ -n "${{ secrets.CONTENTFUL_PREVIEW_TOKEN }}" ]; then
            echo "CONTENTFUL_PREVIEW_TOKEN is set"
          else
            echo "CONTENTFUL_PREVIEW_TOKEN is not set"
          fi
          
      - name: Create production config
        env:
          SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          DELIVERY_TOKEN: ${{ secrets.CONTENTFUL_DELIVERY_TOKEN }}
          PREVIEW_TOKEN: ${{ secrets.CONTENTFUL_PREVIEW_TOKEN }}
        run: |
          echo "Creating production configuration..."
          
          # Copy template to production config
          cp contentful-config.template.js contentful-config.js
          
          echo "Before replacement - checking placeholders:"
          grep -n "CONTENTFUL_" contentful-config.js | head -5
          
          # Use sed for reliable replacement
          sed -i "s/'CONTENTFUL_SPACE_ID'/'$SPACE_ID'/g" contentful-config.js
          sed -i "s/'CONTENTFUL_DELIVERY_TOKEN'/'$DELIVERY_TOKEN'/g" contentful-config.js
          sed -i "s/'CONTENTFUL_PREVIEW_TOKEN'/'$PREVIEW_TOKEN'/g" contentful-config.js
          
          echo "After replacement - checking for remaining placeholders:"
          if grep -q "CONTENTFUL_" contentful-config.js; then
            echo "ERROR: Placeholders still found:"
            grep -n "CONTENTFUL_" contentful-config.js
            exit 1
          else
            echo "SUCCESS: All placeholders replaced"
          fi
          
          echo "First 10 lines of config:"
          head -10 contentful-config.js
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 